name: clean_dart
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  dartz: 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  mockito: ^5.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
